export { default as HeaderCont } from './HeaderCont'
export { default as FooterCont } from './FooterCont'
export { default as MainConts } from './MainConts'
export { default as RankingConts } from './RankingConts'
export { default as Category } from './Category'
